[workspace]
resolver = "2"
members = ["manager", "service", "test_bin"]

[workspace.dependencies]
uni_service = { path = "service" }
uni_service_manager = { path = "manager" }

ctrlc = { version = "3", features = ["termination"] }
dirs = "6"
libc = "0.2"
tracing = { version = "0.1", features = ["std"], default-features = false }
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "std",
], default-features = false }
uni_error = "0.1"
windows-service = "0.8"
